### ISSUE TITLE
please consider forking my own repo

### ISSUE THREAD

**Issue by PeterPawn** [jollyjinx/modfs#1]
Finally I personally switched now to GitHub too and in my opinion it's a good idea now to remove this repo and fork my own instead ... this version is rather old, the current one supports the same (and even later) firmware versions and I'd like to prevent confusions for people searching for "modfs" for FRITZ!OS on GitHub.

Please remove/rename this repo and fork 

https://github.com/PeterPawn/modfs

or add a hint for foreign readers, that this repo is heavily outdated.

Thanks in advance.

**Comment by jollyjinx** [comment]
I've left a comment in the readme and keep this repo for documentation purposes.
